### ISSUE TITLE
pull of docker:dind fails

### ISSUE THREAD

**Issue by cezarnicolescu** [paulgoio/templates#1]
Hi,

I get the error below when I try to use the templates:

```
Starting service gitlab.com/cezarnicolescu/dependency_proxy/containers/docker:dind ...
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image gitlab.com:443/cezarnicolescu/dependency_proxy/containers/docker:dind ...
WARNING: Failed to pull image with policy "always": Error response from daemon: error parsing HTTP 404 response body: unexpected end of JSON input: "" (manager.go:235:0s)
ERROR: Job failed: failed to pull image "gitlab.com:443/cezarnicolescu/dependency_proxy/containers/docker:dind" with specified policies [always]: Error response from daemon: error parsing HTTP 404 response body: unexpected end of JSON input: "" (manager.go:235:0s)
```
Any idea where this might come from?

Many thanks!

**Comment by mrpaulblack** [comment]
Hi @cezarnicolescu ,
sorry for the late reply. My templates only work if you use them in a gitlab org with the dependecy proxy feature enabled. The images get pulled through this dependency proxy so they are cached at gitlab and do not need to get pulled every time from dockerhub. This feature was impl. as a reaction to the rate limiting that dockerhub impl. a while ago.

I am going to refactor my templates in a while completly, but for now you can change this line: https://github.com/paulgoio/templates/blob/d08be0ab34528215abcd93c3270e8692100593c3/all.yml#L16 (and whenever `${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/` is mentioned in the templates) to just `docker:dind` then it will not use the feature and it should just work...


Does this help?

**Comment by mrpaulblack** [comment]
I will close the issue for now; Closing.
